### ISSUE TITLE
닉네임 요청 양식 확인 에러 수정

### ISSUE THREAD

**Issue by thursdaycurry** [week6project/backend#23]
유저 비밀번호 변경 시 닉네임 요청 양식 확인 에러(닉네임 불필요)

**Comment by IOTrue** [comment]
![image](https://user-images.githubusercontent.com/119475769/213090476-6f6249de-f784-43a3-8163-7f1b60574378.png)
![image](https://user-images.githubusercontent.com/119475769/213090546-21019650-3e78-417c-a9fb-cd341698e930.png)

**Comment by jhoon8903** [comment]
해결 완료
