### ISSUE TITLE
Post 게시글 조회 시 쿠키 에러

### ISSUE THREAD

**Issue by thursdaycurry** [week6project/backend#24]
전달된 쿠키에 에러 발생

**Comment by IOTrue** [comment]
![image](https://user-images.githubusercontent.com/119475769/213090632-240c949a-7d40-406b-baee-b9cedc203a2e.png)
![image](https://user-images.githubusercontent.com/119475769/213090665-24eb4f54-939b-4fe5-b54e-f1dbfa116e8c.png)

**Comment by jhoon8903** [comment]
해결 왑료
